/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.androidchat.client;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bubble=0x7f020000;
        public static final int channels=0x7f020001;
        public static final int dude=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int join_channel=0x7f020004;
        public static final int map=0x7f020005;
        public static final int mini_icon=0x7f020006;
    }
    public static final class id {
        public static final int androidchat=0x7f040000;
        public static final int btn_Connect=0x7f040008;
        public static final int btn_ShowOpts=0x7f040009;
        public static final int cGrid=0x7f040001;
        public static final int chanspinner=0x7f04000b;
        public static final int img_AndroidChatLogo=0x7f040007;
        public static final int ircdisp=0x7f040004;
        public static final int ircedit=0x7f040002;
        public static final int ircscroll=0x7f040003;
        public static final int join_chatbut=0x7f04000c;
        public static final int label1=0x7f040010;
        public static final int label2=0x7f040012;
        public static final int label3=0x7f040014;
        public static final int label4=0x7f040016;
        public static final int label5=0x7f040018;
        public static final int mapv=0x7f04000a;
        public static final int optAutoJoin=0x7f040011;
        public static final int optCancel=0x7f04000d;
        public static final int optList=0x7f040013;
        public static final int optNick=0x7f04000f;
        public static final int optPMAlert=0x7f040017;
        public static final int optSave=0x7f04000e;
        public static final int optSend=0x7f040015;
        public static final int start=0x7f040005;
        public static final int stop=0x7f040006;
        public static final int umapv=0x7f040019;
        public static final int userspinner=0x7f04001a;
    }
    public static final class layout {
        public static final int chan_grid=0x7f030000;
        public static final int chat=0x7f030001;
        public static final int irc_control=0x7f030002;
        public static final int main=0x7f030003;
        public static final int main_alt=0x7f030004;
        public static final int map=0x7f030005;
        public static final int options=0x7f030006;
        public static final int usermap=0x7f030007;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int btn_connect=0x7f050001;
        public static final int btn_disconnect=0x7f050002;
        public static final int btn_options=0x7f050003;
        public static final int btn_showwind=0x7f050004;
        public static final int irc_connected=0x7f05000d;
        public static final int irc_connecting=0x7f05000c;
        public static final int irc_disconnected=0x7f05000f;
        public static final int irc_error=0x7f05000e;
        public static final int irc_started=0x7f05000b;
        public static final int irc_stopped=0x7f050010;
        public static final int opt_cancel=0x7f050019;
        public static final int opt_hint1=0x7f050011;
        public static final int opt_hint2=0x7f050012;
        public static final int opt_hint3=0x7f050013;
        public static final int opt_hint4=0x7f050014;
        public static final int opt_hint5=0x7f050015;
        public static final int opt_opt3=0x7f050016;
        public static final int opt_opt4=0x7f050017;
        public static final int opt_opt5=0x7f050018;
        public static final int opt_save=0x7f05001a;
        public static final int ui_getstarted=0x7f050006;
        public static final int ui_newmsg=0x7f050008;
        public static final int ui_newpm=0x7f050007;
        public static final int ui_progress=0x7f05000a;
        public static final int ui_waiting=0x7f050009;
        public static final int welcome=0x7f050005;
    }
}
