/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.androidchat.client;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int arrow=0x7f020000;
        public static final int icon=0x7f020001;
    }
    public static final class id {
        public static final int androidchat=0x7f040000;
        public static final int btn_Connect=0x7f04000a;
        public static final int btn_ShowChan=0x7f04000b;
        public static final int btn_ShowOpts=0x7f040009;
        public static final int img_AndroidChatLogo=0x7f040008;
        public static final int ircback=0x7f040001;
        public static final int ircchannel=0x7f040003;
        public static final int ircdisp=0x7f040005;
        public static final int ircedit=0x7f040004;
        public static final int ircsend=0x7f040002;
        public static final int start=0x7f040006;
        public static final int stop=0x7f040007;
    }
    public static final class layout {
        public static final int chat=0x7f030000;
        public static final int irc_control=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int btn_connect=0x7f050001;
        public static final int btn_disconnect=0x7f050002;
        public static final int irc_connected=0x7f050005;
        public static final int irc_connecting=0x7f050004;
        public static final int irc_disconnected=0x7f050007;
        public static final int irc_error=0x7f050006;
        public static final int irc_started=0x7f050003;
        public static final int irc_stopped=0x7f050008;
    }
}
